### ISSUE TITLE
融入知识推理的实体向量

### ISSUE THREAD

**Issue by ypc-stu** [haidfs/TransE#1]
你好，@haidfs，感谢你刚才给我耐心的解答，我有一个问题想请教你：
如果我想从wikipedia抽取实体，建一个融入知识推理的实体向量，最后的词向量类似与word2vec和glove形式，我应该怎么做吗？

**Comment by haidfs** [comment]
你好，我也刚开始看ai这些东西不久，正在学习中，对于word2vec和glove不了解，关于你的问题说一点个人的看法。个人感觉你想做的项目时需要用到整个知识工程里面的近乎所有步骤的，知识抽取，知识表示，知识融合，知识推理以及知识应用。知识抽取那一块应该涉及到对数据的预处理以及NER，知识融合涉及到同一实体的不同表示的融合，比如A语料主语中说的是北京，B语料中主语说的是中国的首都。这两个其实是一个实体，需要融合。最后知识推理建议不要用TransE，可考虑使用TransD，也可以创造性的和word2Vec的思路结合https://zhuanlan.zhihu.com/p/32993044 。仅仅是个人看法，如有不对希望指正，谢谢

**Comment by ypc-stu** [comment]
@haidfs，对对，我也很认同的观点，但是我导师就说很简单，一个劲儿叫我做一个知识图谱，难受。
非常感谢你的解答哈，同学，good luck

**Comment by haidfs** [comment]
@ypc-stu 你可以问问你导师 感觉他的意思可能是知识库已经有了，是不是维基百科本身就已经构建好了知识库，查了下好像叫wikidata。如果已经构建好了 ，就只需要下载数据，把三元组做一个可解释化的工作，写TransD代码就行了，那样确实简单的。

**Comment by ypc-stu** [comment]
@haidfs，非常感谢耐心的解答，谢谢你

**Comment by haidfs** [comment]
@ypc-stu 没事不必客气 要是觉得ok顺手帮我点个赞吧，谢谢了~

**Comment by ypc-stu** [comment]
ok，已经点了，以后有什么不懂了，再来请教你哈，谢谢帮助~
